language: python

python: 2.7

install:
  # Lektor build dependencies
  - pip install lektor

script:
  - "lektor build --no-prune"

deploy:
  provider: script
  script: "lektor deploy --username $GITHUB_USER --password $GITHUB_PASS"
    on:
      branch: gh-pages
